import type { GameMeta } from '../types';

export const GAMES: GameMeta[] = [
  {
    id: 'snake',
    title: 'Snake',
    description: 'Guía la serpiente, come comida y crece sin chocar. Clásico eterno.',
    emoji: '🐍',
    color: 'var(--game-snake)',
    colorGlow: 'var(--game-snake-glow)',
    tags: ['Clásico', 'Arcade', 'Habilidad'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/snake',
  },
  {
    id: 'tictactoe',
    title: 'Tic Tac Toe',
    description: 'El clásico Triki. Tres en línea gana. Juega contra la IA o un amigo.',
    emoji: '⭕',
    color: 'var(--game-tictactoe)',
    colorGlow: 'var(--game-tictactoe-glow)',
    tags: ['Estrategia', 'Clásico', '2 Jugadores'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/tictactoe',
  },
  {
    id: 'memory',
    title: 'Memory',
    description: 'Encuentra los pares de cartas. Ponle a prueba tu memoria.',
    emoji: '🃏',
    color: 'var(--game-memory)',
    colorGlow: 'var(--game-memory-glow)',
    tags: ['Memoria', 'Concentración'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/memory',
  },
  {
    id: 'hangman',
    title: 'Ahorcado',
    description: 'Adivina la palabra letra por letra antes de que sea demasiado tarde.',
    emoji: '🪤',
    color: 'var(--game-hangman)',
    colorGlow: 'var(--game-hangman-glow)',
    tags: ['Palabras', 'Clásico'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/hangman',
  },
  {
    id: 'minesweeper',
    title: 'Buscaminas',
    description: 'Despeja el tablero sin detonar ninguna mina. Usa la lógica.',
    emoji: '💣',
    color: 'var(--game-minesweeper)',
    colorGlow: 'var(--game-minesweeper-glow)',
    tags: ['Lógica', 'Estrategia'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/minesweeper',
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    description: 'Completa el tablero 9×9 con dígitos del 1 al 9. Reto mental puro.',
    emoji: '🔢',
    color: 'var(--game-sudoku)',
    colorGlow: 'var(--game-sudoku-glow)',
    tags: ['Lógica', 'Números', 'Concentración'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/sudoku',
  },
  {
    id: 'wordsearch',
    title: 'Sopa de Letras',
    description: 'Encuentra todas las palabras ocultas en el tablero de letras.',
    emoji: '🔤',
    color: 'var(--game-wordsearch)',
    colorGlow: 'var(--game-wordsearch-glow)',
    tags: ['Palabras', 'Búsqueda'],
    difficulty: ['easy', 'medium', 'hard'],
    path: '/games/wordsearch',
  },
];

export function getGame(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id);
}
